name: cronjobber
namespace: default
image:
  repository: quay.io/hiddeco/cronjobber
  tag: 0.2.0
replicas: 1
resources:
  requests:
    cpu: 50m
    memory: 64Mi
sidecar:
  enabled: False
  name: init-updatetz
  image:
    repository: quay.io/hiddeco/cronjobber-updatetz
    tag: 0.1.1
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
